#ifndef _MACKEREL_H
#define _MACKEREL_H

#ifdef CONFIG_MACKEREL_08
#define IRQ_NUM_DUART 1
#define IRQ_NUM_TIMER 2
#elif CONFIG_MACKEREL_10
#define IRQ_NUM_IDE 3
#define IRQ_NUM_DUART 5
#define IRQ_NUM_TIMER 6
#endif

// XR68C681 DUART
#ifdef CONFIG_MACKEREL_10
#define DUART1_BASE 0xFF8000
#elif CONFIG_MACKEREL_08
#define DUART1_BASE 0x3FC000
#endif
#define DUART1_MR1A (DUART1_BASE + 0x01)
#define DUART1_MR2A (DUART1_BASE + 0x01)
#define DUART1_SRA (DUART1_BASE + 0x03)
#define DUART1_CSRA (DUART1_BASE + 0x03)
#define DUART1_CRA (DUART1_BASE + 0x05)
#define DUART1_MISR (DUART1_BASE + 0x05)
#define DUART1_RBA (DUART1_BASE + 0x07)
#define DUART1_TBA (DUART1_BASE + 0x07)
#define DUART1_ACR (DUART1_BASE + 0x09)
#define DUART1_ISR (DUART1_BASE + 0x0B)
#define DUART1_IMR (DUART1_BASE + 0x0B)
#define DUART1_CUR (DUART1_BASE + 0x0D)
#define DUART1_CLR (DUART1_BASE + 0x0F)
#define DUART1_MR1B (DUART1_BASE + 0x11)
#define DUART1_MR2B (DUART1_BASE + 0x11)
#define DUART1_SRB (DUART1_BASE + 0x13)
#define DUART1_CSRB (DUART1_BASE + 0x13)
#define DUART1_CRB (DUART1_BASE + 0x15)
#define DUART1_RBB (DUART1_BASE + 0x17)
#define DUART1_TBB (DUART1_BASE + 0x17)
#define DUART1_IVR (DUART1_BASE + 0x19)
#define DUART1_OPCR (DUART1_BASE + 0x1B)
#define DUART1_OPR (DUART1_BASE + 0x1D)
#define DUART1_OPR_RESET (DUART1_BASE + 0x1F)

// IDE
#ifdef CONFIG_MACKEREL_10
#define MACKEREL_IDE_BASE 0xFFC000
#define MACKEREL_IDE_DATA MACKEREL_IDE_BASE + 0x00
#define MACKEREL_IDE_FEATURE MACKEREL_IDE_BASE + 0x02
#define MACKEREL_IDE_SECTOR_COUNT MACKEREL_IDE_BASE + 0x04
#define MACKEREL_IDE_SECTOR_START MACKEREL_IDE_BASE + 0x06
#define MACKEREL_IDE_LBA_MID MACKEREL_IDE_BASE + 0x08
#define MACKEREL_IDE_LBA_HIGH MACKEREL_IDE_BASE + 0x0A
#define MACKEREL_IDE_DRIVE_SEL MACKEREL_IDE_BASE + 0x0C
#define MACKEREL_IDE_STATUS MACKEREL_IDE_BASE + 0x0E
#define MACKEREL_IDE_COMMAND MACKEREL_IDE_BASE + 0x0E

#define MACKEREL_IDE_ALT_STATUS 0xFF4000 + 0x0C  // aka Device Control
#endif

// Interrupt bits
#define DUART_INTR_COUNTER 0b0001000
#define DUART_INTR_RXRDY 0b00100000

// Get the value at a memory address
#define MEM(address) (*(volatile unsigned char *)(address))
#define MEM16(address) (*(volatile unsigned short *)(address))
#define MEM32(address) (*(volatile unsigned int *)(address))

// DUART
void duart_putc(char c);
char duart_getc(void);

#endif
